"""added difficulty column

Revision ID: 72634f4ba805
Revises: 
Create Date: 2026-02-06 14:19:37.483198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72634f4ba805'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('difficulty')

    # ### end Alembic commands ###
